# NumPy Giriş

In [1]:
a = [1,2,3,4]
b = [2,3,4,5]

ab = []                        

for i in range(0, len(a)):
  ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [2]:
import numpy as np 

a = np.array([1,2,3,4])

b = np.array([2,3,4,5])

a * b

array([ 2,  6, 12, 20])

In [3]:
x = 9

In [4]:
who

a	 ab	 b	 i	 np	 x	 


In [5]:
x

9

In [6]:
L = [1,2,"a",1.2]
L

[1, 2, 'a', 1.2]

In [7]:
[type(i) for i in L]

[int, int, str, float]

# NumPy Arrayleri Oluşturma

## Listelerden Array Oluşturmak

In [8]:
import numpy as np 

np.array([12,33,4,5])

a = np.array([12,33,4,5])

a

type(a)

numpy.ndarray

In [9]:
np.array([3.14, 4,6,1.2])

array([3.14, 4.  , 6.  , 1.2 ])

In [10]:
np.array([3.14, 4,6,1.2], dtype = 'float32')

array([3.14, 4.  , 6.  , 1.2 ], dtype=float32)

In [11]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

#deneme

In [13]:
z=np.zeros((5,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
z[1:4,1:4]=1
z

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.full((2,3), 9)

array([[9, 9, 9],
       [9, 9, 9]])

In [16]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [17]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [18]:
np.random.normal(0,1, (3,4))

array([[-0.46535181, -1.53339733,  0.11313512, -0.01510375],
       [ 0.01575585,  0.78946849,  1.75905004,  0.00346667],
       [ 0.17236271,  0.19696085, -0.38718277,  0.06621729]])

In [19]:
np.random.randint(0,10, (2,2))

array([[6, 1],
       [4, 4]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

deneme

In [21]:
np.eye(5,k=1,M=6)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Numpy Biçimlendirme

* **ndim**: boyut sayısı

* **shape**: boyut bilgisi

* **size**: toplam eleman sayısı

* **dtype**: array veri tipi

In [22]:
import numpy as np
a = np.random.randint(10, size = 10)
a.ndim
a.shape
a.size
a.dtype

dtype('int32')

In [23]:
a = np.random.randint(10, size = (10, 5))
a

array([[6, 3, 4, 7, 2],
       [6, 1, 9, 9, 9],
       [8, 5, 5, 6, 5],
       [3, 0, 5, 4, 9],
       [8, 7, 2, 4, 6],
       [9, 1, 8, 1, 7],
       [6, 9, 7, 0, 9],
       [1, 5, 4, 9, 7],
       [5, 6, 7, 6, 4],
       [5, 6, 8, 1, 2]])

In [24]:
a.ndim

2

In [25]:
a.shape

(10, 5)

In [26]:
a.size

50

In [27]:
a.dtype

dtype('int32')

In [28]:
a = np.random.randint(10, size = (3,5,2))
a

array([[[1, 9],
        [7, 3],
        [5, 7],
        [9, 8],
        [6, 6]],

       [[7, 3],
        [7, 9],
        [6, 8],
        [9, 9],
        [0, 4]],

       [[9, 6],
        [5, 6],
        [0, 8],
        [5, 5],
        [4, 3]]])

In [29]:
a.ndim

3

In [30]:
a.shape

(3, 5, 2)

In [31]:
a.size

30

In [32]:
a.dtype

dtype('int32')

In [33]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a = np.array([1,2,3])

In [36]:
a

array([1, 2, 3])

In [37]:
b = a.reshape((1,3))

In [38]:
b.ndim

2

In [39]:
a

array([1, 2, 3])

In [40]:
a[np.newaxis, :]

array([[1, 2, 3]])

In [41]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [42]:
#tek boyutlu

In [43]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [44]:
x

array([1, 2, 3])

In [45]:
y

array([4, 5, 6])

In [46]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [47]:
z = [1,2,3]

In [48]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [49]:
#iki boyutlu

In [50]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [52]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [53]:
#farklı boyutlu 

In [54]:
a = np.array([1, 2, 3])

b = np.array([[9, 8, 7], 
              [6, 5, 4]])

In [55]:
a

array([1, 2, 3])

In [56]:
b

array([[9, 8, 7],
       [6, 5, 4]])

In [57]:
np.vstack([a,b])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [58]:
a = np.array([[99],
              [99]])

In [59]:
a

array([[99],
       [99]])

In [60]:
np.hstack([a,b])

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

In [61]:
#array ayirma splitting

In [62]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x

[1, 2, 3, 99, 99, 3, 2, 1]

In [63]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [64]:
a,b,c = np.split(x, [3,5])

In [65]:
a

array([1, 2, 3])

In [66]:
b

array([99, 99])

In [67]:
c

array([3, 2, 1])

In [68]:
#np.split(m,[2,2])

In [69]:
m = np.arange(16).reshape((4, 4))

In [70]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [71]:
ust, alt = np.vsplit(m, [2])

In [72]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [73]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [75]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
sag, sol = np.hsplit(m, [2])

In [77]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [78]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [79]:
#array siralama 

In [80]:
v = np.array([2, 1, 4, 3, 5])
v

array([2, 1, 4, 3, 5])

In [81]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [82]:
v

array([2, 1, 4, 3, 5])

In [83]:
v.sort()

In [84]:
v

array([1, 2, 3, 4, 5])

In [85]:
v = np.array([2, 1, 4, 3, 5])

In [86]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [87]:
i = np.argsort(v)

In [88]:
i

array([1, 0, 3, 2, 4], dtype=int64)

In [89]:
v

array([2, 1, 4, 3, 5])

In [90]:
v[i]

array([1, 2, 3, 4, 5])

# NumPy Eleman İşlemleri

## Index ile Elemanlara Erişmek

In [91]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([2, 4, 6, 9, 2, 3, 0, 1, 0, 1])

In [92]:
a[0]

2

In [93]:
a[-2]

0

In [94]:
a[0] = 1

In [95]:
a

array([1, 4, 6, 9, 2, 3, 0, 1, 0, 1])

In [96]:
a = np.random.randint(10, size = (3, 5))
a

array([[9, 8, 6, 7, 0],
       [3, 5, 0, 9, 2],
       [1, 6, 9, 9, 4]])

In [97]:
a[0,0]

9

In [98]:
a[1,1]

5

In [99]:
a[0,0] = 1

In [100]:
a[0,0]

1

In [101]:
a[0,0] = 2.2

In [102]:
a[0,0]

2

## Slicing ile Array Alt Kümesine Erişmek

In [103]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [104]:
a[0:3]

array([20, 21, 22])

In [105]:
a[:3]

array([20, 21, 22])

In [106]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [107]:
a[::2]

array([20, 22, 24, 26, 28])

In [108]:
a[1::2]

array([21, 23, 25, 27, 29])

In [109]:
a[2::2]

array([22, 24, 26, 28])

In [110]:
a[1::3]

array([21, 24, 27])

In [111]:
a = np.random.randint(10, size = (5, 5))
a

array([[1, 4, 6, 4, 0],
       [5, 6, 7, 1, 3],
       [3, 1, 5, 0, 6],
       [4, 8, 8, 0, 3],
       [0, 6, 2, 5, 8]])

In [112]:
a[:,0]

array([1, 5, 3, 4, 0])

In [113]:
a[:,1]

array([4, 6, 1, 8, 6])

In [114]:
a[:,4]

array([0, 3, 6, 3, 8])

In [115]:
a

array([[1, 4, 6, 4, 0],
       [5, 6, 7, 1, 3],
       [3, 1, 5, 0, 6],
       [4, 8, 8, 0, 3],
       [0, 6, 2, 5, 8]])

In [116]:
a[4,:]

array([0, 6, 2, 5, 8])

In [117]:
a[0]

array([1, 4, 6, 4, 0])

In [118]:
a[:2,:3]

array([[1, 4, 6],
       [5, 6, 7]])

In [119]:
a[0:2,0:3]

array([[1, 4, 6],
       [5, 6, 7]])

In [120]:
a[::,:2]

array([[1, 4],
       [5, 6],
       [3, 1],
       [4, 8],
       [0, 6]])

In [121]:
a[:,:2]

array([[1, 4],
       [5, 6],
       [3, 1],
       [4, 8],
       [0, 6]])

In [122]:
a[1:3,0:2]

array([[5, 6],
       [3, 1]])

In [123]:
a = np.random.randint(10, size = (5, 5))
a

array([[9, 0, 4, 0, 9],
       [1, 8, 7, 6, 5],
       [6, 1, 5, 7, 4],
       [9, 5, 1, 3, 0],
       [3, 6, 1, 6, 2]])

In [124]:
alt_a = a[0:3,0:2]

In [125]:
alt_a

array([[9, 0],
       [1, 8],
       [6, 1]])

In [126]:
alt_a[0,0] = 9999
alt_a[1,1] = 9999

In [127]:
alt_a

array([[9999,    0],
       [   1, 9999],
       [   6,    1]])

In [128]:
a

array([[9999,    0,    4,    0,    9],
       [   1, 9999,    7,    6,    5],
       [   6,    1,    5,    7,    4],
       [   9,    5,    1,    3,    0],
       [   3,    6,    1,    6,    2]])

In [129]:
alt_b = a[0:3,0:2].copy()

In [130]:
alt_b

array([[9999,    0],
       [   1, 9999],
       [   6,    1]])

In [131]:
alt_b[0,0] = 9999
alt_b[1,1] = 9999

In [132]:
a

array([[9999,    0,    4,    0,    9],
       [   1, 9999,    7,    6,    5],
       [   6,    1,    5,    7,    4],
       [   9,    5,    1,    3,    0],
       [   3,    6,    1,    6,    2]])

## Fancy Index ile Eleman İşlemleri

In [133]:
v[1]
v[3]

3

In [134]:
[v[1], v[3]]

[1, 3]

In [135]:
v = np.arange(10)

In [136]:
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
al_getir = [1,3,5]

In [138]:
v[al_getir]

array([1, 3, 5])

In [139]:
m = np.arange(9).reshape((3, 3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [140]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [141]:
m[satir, sutun]

array([1, 5])

In [142]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [143]:
m[0, [1,2]]

array([1, 2])

In [144]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [145]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
index = np.array([0,1,2])
index

array([0, 1, 2])

In [147]:
v[index] = 99

In [148]:
v

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [149]:
v[[0,1]] = [4,6]

In [150]:
v

array([ 4,  6, 99,  3,  4,  5,  6,  7,  8,  9])

# Koşullu Eleman İşlemleri

In [151]:
v = np.array([1,2,3,4,5])

In [152]:
v > 3

array([False, False, False,  True,  True])

In [153]:
v < 3

array([ True,  True, False, False, False])

In [154]:
v <= 3

array([ True,  True,  True, False, False])

In [155]:
v == 3

array([False, False,  True, False, False])

In [156]:
v != 3

array([ True,  True, False,  True,  True])

In [157]:
2*v

array([ 2,  4,  6,  8, 10])

In [158]:
3*v

array([ 3,  6,  9, 12, 15])

In [159]:
(2 * v)

array([ 2,  4,  6,  8, 10])

In [160]:
(v ** 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [161]:
(2 * v) == (v ** 2)

array([False,  True, False, False, False])

In [162]:
#ufunc

np.equal
np.not_equal
np.less
np.less_equal
np.greater
np.greater_equal

In [163]:
v = np.array([1,2,3,4,5])

In [164]:
np.equal(3,v)

array([False, False,  True, False, False])

In [165]:
np.equal([0,1,3], np.arange(3))

array([ True,  True, False])

In [166]:
np.arange(3)

array([0, 1, 2])

In [167]:
v = np.random.randint(0, 10, (3, 3))
v

array([[8, 9, 1],
       [6, 1, 7],
       [6, 5, 0]])

In [168]:
v > 5

array([[ True,  True, False],
       [ True, False,  True],
       [ True, False, False]])

In [169]:
np.sum(v > 5)

5

In [170]:
np.sum((v > 3) & (v < 7))

3

In [171]:
(v > 3) & (v < 7)

array([[False, False, False],
       [ True, False, False],
       [ True,  True, False]])

In [172]:
np.sum((v > 3) | (v < 7))

9

In [173]:
np.sum(v > 4, axis = 1)

array([2, 2, 2])

In [174]:
np.sum(v > 4, axis = 0)

array([3, 2, 1])

In [175]:
np.all(v > 4)

False

In [176]:
np.all(v > 0)

False

In [177]:
np.any(v > 4)

True

In [178]:
np.all(v > 4, axis = 0)

array([ True, False, False])

In [179]:
np.all(v > 4, axis = 1)

array([False, False, False])

In [180]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [181]:
v[0]

1

In [182]:
v > 3

array([False, False, False,  True,  True])

In [183]:
v[(v > 1) & (v < 5)]

array([2, 3, 4])

# NumPy Hesaplamalı İşlemler

In [184]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [185]:
a - 1

array([-1,  0,  1,  2,  3])

In [186]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. ])

In [187]:
a * 5 

array([ 0,  5, 10, 15, 20])

In [188]:
a ** 2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [189]:
a % 2

array([0, 1, 0, 1, 0], dtype=int32)

In [190]:
5*(a/2*9)

array([ 0. , 22.5, 45. , 67.5, 90. ])

In [191]:
a

array([0, 1, 2, 3, 4])

In [192]:
np.add(a,2)

array([2, 3, 4, 5, 6])

In [193]:
np.subtract(a,1)

array([-1,  0,  1,  2,  3])

In [194]:
np.multiply(a,3)

array([ 0,  3,  6,  9, 12])

In [195]:
np.divide(a,3)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333])

In [196]:
np.power(a,3)

array([ 0,  1,  8, 27, 64], dtype=int32)

In [197]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [198]:
np.add.reduce(a)

15

In [199]:
np.add.accumulate(a)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [200]:
a = np.random.normal(0, 1, 30)
a

array([ 0.38739647,  0.17516186,  0.23091977,  0.48060514, -1.70510623,
        0.5003329 ,  1.44518055, -1.37117446,  0.80651182,  1.26173193,
        0.89394519,  0.42369909, -1.48817081, -0.3629774 , -0.46498795,
       -0.38111591, -1.16482839,  1.00716135,  0.72558768,  1.15014265,
        0.46946227, -0.94160509,  1.14259413, -0.57767813, -0.08216808,
       -0.7192487 , -0.5622376 , -1.3458085 , -0.39666538, -0.47292178])

In [201]:
np.mean(a)

-0.0312087197207955

In [202]:
np.std(a)

0.8848788830209702

In [203]:
np.var(a)

0.7830106376164397

In [204]:
np.median(a)

0.046496885366741236

In [205]:
sum(a)

-0.9362615916238655

np.nanmean(a)

np.nanstd(a)

np.nanvar(a)

np.nanargmin(a) 

np.nanargmax(a) 

np.nanmedian(a)

In [206]:
np.min(a)

-1.705106228000283

In [207]:
np.max(a)

1.4451805462611986

In [208]:
a = np.random.normal(0, 1, (3,3))
a

array([[-1.40485597,  0.99278405,  0.40458199],
       [ 0.943913  , -0.1407523 ,  0.55975965],
       [ 0.23596928, -0.2381368 , -0.25888705]])

In [209]:
a.sum()

1.0943758451497294

In [210]:
a.sum(axis = 1)

array([-0.00748993,  1.36292036, -0.26105458])

# Farklı Boyutlu Arrayler ile Birlikte Çalışmak (broadcasting)

In [211]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

a + b

array([2, 4, 6])

In [212]:
m = np.ones((3, 3))
m

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [213]:
a

array([1, 2, 3])

In [214]:
a + m

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [215]:
a = np.arange(3)
a

array([0, 1, 2])

In [216]:
b = np.arange(3)[:, np.newaxis]
b

array([[0],
       [1],
       [2]])

In [217]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [218]:
M = np.ones((2, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [219]:
a = np.arange(3)
a

array([0, 1, 2])

In [220]:
a + M

array([[1., 2., 3.],
       [1., 2., 3.]])

In [221]:
a = np.arange(3).reshape((3, 1))
a

array([[0],
       [1],
       [2]])

In [222]:
b = np.arange(3)
b

array([0, 1, 2])

In [223]:
a.shape

(3, 1)

In [224]:
b.shape

(3,)

In [225]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [226]:
m = np.ones((3,2))
m

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [227]:
a = np.arange(3)
a

array([0, 1, 2])

In [228]:
m.shape

(3, 2)

In [229]:
a.shape

(3,)

# Numpy Yapısal Array'ler

## Hello! Good Bye! Numpy

In [230]:
isim = ['ali', 'veli', 'isik']
yas = [25, 22, 19]
boy = [168, 159, 172]

In [231]:
data = np.zeros(3, dtype={'names':('isim', 'yas', 'boy'),
                          'formats':('U10', 'i4', 'f8')})

In [232]:
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [233]:
data['isim'] = isim
data['yas'] = yas
data['boy'] = boy

In [234]:
data

array([('ali', 25, 168.), ('veli', 22, 159.), ('isik', 19, 172.)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [235]:
data['isim']

array(['ali', 'veli', 'isik'], dtype='<U10')

In [236]:
data[0]

('ali', 25, 168.)

In [237]:
data[data['yas'] < 25]['isim']

array(['veli', 'isik'], dtype='<U10')

# Pandas

## Pandas Series

In [238]:
import numpy as np
import pandas as pd

In [239]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [240]:
seri = pd.Series([1,2,3,4])

In [241]:
type(seri)

pandas.core.series.Series

In [242]:
seri.axes

[RangeIndex(start=0, stop=4, step=1)]

In [243]:
seri.dtype

dtype('int64')

In [244]:
seri.empty

False

In [245]:
seri.ndim

1

In [246]:
seri.size

4

In [247]:
seri.values

array([1, 2, 3, 4], dtype=int64)

In [248]:
seri.head(2)

0    1
1    2
dtype: int64

In [249]:
seri[0:3]

0    1
1    2
2    3
dtype: int64

In [250]:
seri.tail(2)

2    3
3    4
dtype: int64

In [251]:
a = np.array([1,2,3,566,88])
a

array([  1,   2,   3, 566,  88])

In [252]:
type(a)

numpy.ndarray

In [253]:
seri = pd.Series(a)

In [254]:
seri

0      1
1      2
2      3
3    566
4     88
dtype: int32

In [255]:
seri.index

RangeIndex(start=0, stop=5, step=1)

In [256]:
seri[0]

1

In [257]:
pd.Series([1,5,0.9,34], index = [1,3,5,7])

1     1.0
3     5.0
5     0.9
7    34.0
dtype: float64

In [258]:
seri = pd.Series([1,5,0.9,34], index = ['a','b','c','d'])

In [259]:
seri["a"]

1.0

In [260]:
sozluk = { "reg" : 10, "loj" : 11, "cart" : 12}

In [261]:
sozluk

{'reg': 10, 'loj': 11, 'cart': 12}

In [262]:
seri = pd.Series(sozluk)

In [263]:
seri["reg"]

10

In [264]:
seri["loj":"cart"]

loj     11
cart    12
dtype: int64

In [265]:
seri

reg     10
loj     11
cart    12
dtype: int64

In [266]:
pd.concat([seri, seri])

reg     10
loj     11
cart    12
reg     10
loj     11
cart    12
dtype: int64

In [267]:
seri.append(seri)

reg     10
loj     11
cart    12
reg     10
loj     11
cart    12
dtype: int64

In [268]:
seri

reg     10
loj     11
cart    12
dtype: int64

## Serilerde Eleman İşlemleri

In [269]:
a = np.array([1, 2, 3,33,55,66])
seri = pd.Series(a)
seri

0     1
1     2
2     3
3    33
4    55
5    66
dtype: int32

In [270]:
seri[0]

1

In [271]:
seri[0:3]

0    1
1    2
2    3
dtype: int32

In [272]:
seri = pd.Series([121, 200, 150, 99], 
                 index=["reg", "loj", "cart", "rf"])
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [273]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [274]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [275]:
print(seri.items())

In [276]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [277]:
seri.values

array([121, 200, 150,  99], dtype=int64)

In [278]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [279]:
"reg" in seri

True

In [280]:
seri["reg"]

121

In [281]:
seri[['rf', 'reg']]

rf      99
reg    121
dtype: int64

In [282]:
seri["rf"] = 125

In [283]:
seri

reg     121
loj     200
cart    150
rf      125
dtype: int64

In [284]:
seri['loj': 'rf']

loj     200
cart    150
rf      125
dtype: int64

In [285]:
seri[0:2]

reg    121
loj    200
dtype: int64

In [286]:
seri = pd.Series([121, 200, 150, 99], index=["reg", "loj", "cart", "rf"])
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [287]:
seri[(seri > 125) & (seri < 200)]

cart    150
dtype: int64

In [288]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [289]:
#data[0] error

In [290]:
data[1]

'a'

In [291]:
data[1:3]

3    b
5    c
dtype: object

In [292]:
data[0:3]

1    a
3    b
5    c
dtype: object

In [293]:
# loc label based indexing, tanımlandığı şekli ile index yakalamak

In [294]:
data

1    a
3    b
5    c
dtype: object

In [295]:
data.loc[0:3]

1    a
3    b
dtype: object

In [296]:
# iloc positional indexing, indexi sıfırlayarak yakalamak

In [297]:
data

1    a
3    b
5    c
dtype: object

In [298]:
#data.loc[2] error

In [299]:
data.iloc[2]

'c'

In [300]:
data.iloc[0:3]

1    a
3    b
5    c
dtype: object