# NumPy Giriş

In [1]:
a = [1,2,3,4]
b = [2,3,4,5]

ab = []                        

for i in range(0, len(a)):
  ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [2]:
import numpy as np 

a = np.array([1,2,3,4])

b = np.array([2,3,4,5])

a * b

array([ 2,  6, 12, 20])

In [3]:
x = 9

In [4]:
who

a	 ab	 b	 i	 np	 x	 


In [5]:
x

9

In [6]:
L = [1,2,"a",1.2]
L

[1, 2, 'a', 1.2]

In [7]:
[type(i) for i in L]

[int, int, str, float]

# NumPy Arrayleri Oluşturma

## Listelerden Array Oluşturmak

In [8]:
import numpy as np 

np.array([12,33,4,5])

a = np.array([12,33,4,5])

a

type(a)

numpy.ndarray

In [9]:
np.array([3.14, 4,6,1.2])

array([3.14, 4.  , 6.  , 1.2 ])

In [10]:
np.array([3.14, 4,6,1.2], dtype = 'float32')

array([3.14, 4.  , 6.  , 1.2 ], dtype=float32)

In [11]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.full((2,3), 9)

array([[9, 9, 9],
       [9, 9, 9]])

In [14]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [15]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [16]:
np.random.normal(0,1, (3,4))

array([[ 1.23669969,  0.80039489,  0.12213732, -0.38336537],
       [-0.44957819,  1.91132259, -1.29297248,  1.12773164],
       [ 0.41737845, -0.87626983, -0.07108058, -0.66157691]])

In [17]:
np.random.randint(0,10, (2,2))

array([[4, 6],
       [4, 9]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Numpy Biçimlendirme

* **ndim**: boyut sayısı

* **shape**: boyut bilgisi

* **size**: toplam eleman sayısı

* **dtype**: array veri tipi

In [19]:
import numpy as np
a = np.random.randint(10, size = 10)
a.ndim
a.shape
a.size
a.dtype

dtype('int32')

In [20]:
a = np.random.randint(10, size = (10, 5))
a

array([[3, 0, 7, 6, 1],
       [6, 5, 6, 8, 5],
       [8, 6, 1, 8, 1],
       [3, 1, 1, 5, 6],
       [1, 9, 1, 4, 4],
       [8, 0, 1, 1, 8],
       [8, 0, 9, 6, 2],
       [3, 8, 9, 2, 6],
       [1, 5, 9, 0, 1],
       [6, 2, 5, 8, 1]])

In [21]:
a.ndim

2

In [22]:
a.shape

(10, 5)

In [23]:
a.size

50

In [24]:
a.dtype

dtype('int32')

In [25]:
a = np.random.randint(10, size = (3,5,2))
a

array([[[5, 9],
        [0, 8],
        [1, 9],
        [7, 2],
        [7, 2]],

       [[7, 0],
        [8, 6],
        [3, 7],
        [8, 3],
        [9, 4]],

       [[8, 3],
        [5, 7],
        [4, 6],
        [7, 6],
        [0, 3]]])

In [26]:
a.ndim

3

In [27]:
a.shape

(3, 5, 2)

In [28]:
a.size

30

In [29]:
a.dtype

dtype('int32')

In [30]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
a = np.array([1,2,3])

In [33]:
a

array([1, 2, 3])

In [34]:
b = a.reshape((1,3))

In [35]:
b.ndim

2

In [36]:
a

array([1, 2, 3])

In [37]:
a[np.newaxis, :]

array([[1, 2, 3]])

In [38]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [39]:
#tek boyutlu

In [40]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [41]:
x

array([1, 2, 3])

In [42]:
y

array([4, 5, 6])

In [43]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [44]:
z = [1,2,3]

In [45]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [46]:
#iki boyutlu

In [47]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [49]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [50]:
#farklı boyutlu 

In [51]:
a = np.array([1, 2, 3])

b = np.array([[9, 8, 7], 
              [6, 5, 4]])

In [52]:
a

array([1, 2, 3])

In [53]:
b

array([[9, 8, 7],
       [6, 5, 4]])

In [54]:
np.vstack([a,b])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [55]:
a = np.array([[99],
              [99]])

In [56]:
a

array([[99],
       [99]])

In [57]:
np.hstack([a,b])

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

In [58]:
#array ayirma splitting

In [59]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x

[1, 2, 3, 99, 99, 3, 2, 1]

In [60]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [61]:
a,b,c = np.split(x, [3,5])

In [62]:
a

array([1, 2, 3])

In [63]:
b

array([99, 99])

In [64]:
c

array([3, 2, 1])

In [65]:
m = np.arange(16).reshape((4, 4))

In [66]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [67]:
ust, alt = np.vsplit(m, [2])

In [68]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [69]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [71]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
sag, sol = np.hsplit(m, [2])

In [73]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [74]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [75]:
#array siralama 

In [76]:
v = np.array([2, 1, 4, 3, 5])
v

array([2, 1, 4, 3, 5])

In [77]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [78]:
v

array([2, 1, 4, 3, 5])

In [79]:
v.sort()

In [80]:
v

array([1, 2, 3, 4, 5])

In [81]:
v = np.array([2, 1, 4, 3, 5])

In [82]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [83]:
i = np.argsort(v)

In [84]:
i

array([1, 0, 3, 2, 4], dtype=int64)

In [85]:
v

array([2, 1, 4, 3, 5])

In [86]:
v[i]

array([1, 2, 3, 4, 5])

# NumPy Eleman İşlemleri

## Index ile Elemanlara Erişmek

In [87]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([5, 2, 4, 4, 1, 6, 2, 7, 4, 0])

In [88]:
a[0]

5

In [89]:
a[-2]

4

In [90]:
a[0] = 1

In [91]:
a

array([1, 2, 4, 4, 1, 6, 2, 7, 4, 0])

In [92]:
a = np.random.randint(10, size = (3, 5))
a

array([[5, 9, 9, 0, 8],
       [1, 7, 9, 4, 5],
       [1, 3, 7, 5, 3]])

In [93]:
a[0,0]

5

In [94]:
a[1,1]

7

In [95]:
a[0,0] = 1

In [96]:
a[0,0]

1

In [97]:
a[0,0] = 2.2

In [98]:
a[0,0]

2

## Slicing ile Array Alt Kümesine Erişmek

In [99]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [100]:
a[0:3]

array([20, 21, 22])

In [101]:
a[:3]

array([20, 21, 22])

In [102]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [103]:
a[::2]

array([20, 22, 24, 26, 28])

In [104]:
a[1::2]

array([21, 23, 25, 27, 29])

In [105]:
a[2::2]

array([22, 24, 26, 28])

In [106]:
a[1::3]

array([21, 24, 27])

In [107]:
a = np.random.randint(10, size = (5, 5))
a

array([[5, 7, 8, 6, 5],
       [3, 1, 7, 9, 6],
       [2, 2, 8, 1, 8],
       [2, 7, 0, 6, 8],
       [5, 0, 9, 5, 0]])

In [108]:
a[:,0]

array([5, 3, 2, 2, 5])

In [109]:
a[:,1]

array([7, 1, 2, 7, 0])

In [110]:
a[:,4]

array([5, 6, 8, 8, 0])

In [111]:
a

array([[5, 7, 8, 6, 5],
       [3, 1, 7, 9, 6],
       [2, 2, 8, 1, 8],
       [2, 7, 0, 6, 8],
       [5, 0, 9, 5, 0]])

In [112]:
a[4,:]

array([5, 0, 9, 5, 0])

In [113]:
a[0]

array([5, 7, 8, 6, 5])

In [114]:
a[:2,:3]

array([[5, 7, 8],
       [3, 1, 7]])

In [115]:
a[0:2,0:3]

array([[5, 7, 8],
       [3, 1, 7]])

In [116]:
a[::,:2]

array([[5, 7],
       [3, 1],
       [2, 2],
       [2, 7],
       [5, 0]])

In [117]:
a[:,:2]

array([[5, 7],
       [3, 1],
       [2, 2],
       [2, 7],
       [5, 0]])

In [118]:
a[1:3,0:2]

array([[3, 1],
       [2, 2]])

In [119]:
a = np.random.randint(10, size = (5, 5))
a

array([[8, 2, 5, 9, 0],
       [2, 9, 1, 6, 0],
       [1, 9, 5, 4, 0],
       [5, 2, 2, 2, 4],
       [0, 0, 1, 1, 4]])

In [120]:
alt_a = a[0:3,0:2]

In [121]:
alt_a

array([[8, 2],
       [2, 9],
       [1, 9]])

In [122]:
alt_a[0,0] = 9999
alt_a[1,1] = 9999

In [123]:
alt_a

array([[9999,    2],
       [   2, 9999],
       [   1,    9]])

In [124]:
a

array([[9999,    2,    5,    9,    0],
       [   2, 9999,    1,    6,    0],
       [   1,    9,    5,    4,    0],
       [   5,    2,    2,    2,    4],
       [   0,    0,    1,    1,    4]])

In [125]:
alt_b = a[0:3,0:2].copy()

In [126]:
alt_b

array([[9999,    2],
       [   2, 9999],
       [   1,    9]])

In [127]:
alt_b[0,0] = 9999
alt_b[1,1] = 9999

In [128]:
a

array([[9999,    2,    5,    9,    0],
       [   2, 9999,    1,    6,    0],
       [   1,    9,    5,    4,    0],
       [   5,    2,    2,    2,    4],
       [   0,    0,    1,    1,    4]])

## Fancy Index ile Eleman İşlemleri

In [129]:
v[1]
v[3]

3

In [130]:
[v[1], v[3]]

[1, 3]

In [131]:
v = np.arange(10)

In [132]:
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
al_getir = [1,3,5]

In [134]:
v[al_getir]

array([1, 3, 5])

In [135]:
m = np.arange(9).reshape((3, 3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [136]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [137]:
m[satir, sutun]

array([1, 5])

In [138]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [139]:
m[0, [1,2]]

array([1, 2])

In [140]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [141]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
index = np.array([0,1,2])
index

array([0, 1, 2])

In [143]:
v[index] = 99

In [144]:
v

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [145]:
v[[0,1]] = [4,6]

In [146]:
v

array([ 4,  6, 99,  3,  4,  5,  6,  7,  8,  9])

# Koşullu Eleman İşlemleri

In [147]:
v = np.array([1,2,3,4,5])

In [148]:
v > 3

array([False, False, False,  True,  True])

In [149]:
v < 3

array([ True,  True, False, False, False])

In [150]:
v <= 3

array([ True,  True,  True, False, False])

In [151]:
v == 3

array([False, False,  True, False, False])

In [152]:
v != 3

array([ True,  True, False,  True,  True])

In [153]:
(2 * v)

array([ 2,  4,  6,  8, 10])

In [154]:
(v ** 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [155]:
(2 * v) == (v ** 2)

array([False,  True, False, False, False])

In [156]:
#ufunc

np.equal
np.not_equal
np.less
np.less_equal
np.greater
np.greater_equal

In [157]:
v = np.array([1,2,3,4,5])

In [158]:
np.equal(3,v)

array([False, False,  True, False, False])

In [159]:
np.equal([0,1,3], np.arange(3))

array([ True,  True, False])

In [160]:
np.arange(3)

array([0, 1, 2])

In [161]:
v = np.random.randint(0, 10, (3, 3))
v

array([[7, 4, 9],
       [7, 6, 0],
       [7, 3, 4]])

In [162]:
v > 5

array([[ True, False,  True],
       [ True,  True, False],
       [ True, False, False]])

In [163]:
np.sum(v > 5)

5

In [164]:
np.sum((v > 3) & (v < 7))

3

In [165]:
(v > 3) & (v < 7)

array([[False,  True, False],
       [False,  True, False],
       [False, False,  True]])

In [166]:
np.sum((v > 3) | (v < 7))

9

In [167]:
np.sum(v > 4, axis = 1)

array([2, 2, 1])

In [168]:
np.sum(v > 4, axis = 0)

array([3, 1, 1])

In [169]:
np.all(v > 4)

False

In [170]:
np.all(v > 0)

False

In [171]:
np.any(v > 4)

True

In [172]:
np.all(v > 4, axis = 0)

array([ True, False, False])

In [173]:
np.all(v > 4, axis = 1)

array([False, False, False])

In [174]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [175]:
v[0]

1

In [176]:
v > 3

array([False, False, False,  True,  True])

In [177]:
v[(v > 1) & (v < 5)]

array([2, 3, 4])

# NumPy Hesaplamalı İşlemler

In [178]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [179]:
a - 1

array([-1,  0,  1,  2,  3])

In [180]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. ])

In [181]:
a * 5 

array([ 0,  5, 10, 15, 20])

In [182]:
a ** 2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [183]:
a % 2

array([0, 1, 0, 1, 0], dtype=int32)

In [184]:
5*(a/2*9)

array([ 0. , 22.5, 45. , 67.5, 90. ])

In [185]:
a

array([0, 1, 2, 3, 4])

In [186]:
np.add(a,2)

array([2, 3, 4, 5, 6])

In [187]:
np.subtract(a,1)

array([-1,  0,  1,  2,  3])

In [188]:
np.multiply(a,3)

array([ 0,  3,  6,  9, 12])

In [189]:
np.divide(a,3)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333])

In [190]:
np.power(a,3)

array([ 0,  1,  8, 27, 64], dtype=int32)

In [191]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [192]:
np.add.reduce(a)

15

In [193]:
np.add.accumulate(a)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [194]:
a = np.random.normal(0, 1, 30)
a

array([ 0.34244173,  2.19945957, -0.64089868, -1.49596905,  0.7892211 ,
        1.66386874, -0.26777169, -0.76676178,  0.51042314,  1.93829322,
       -0.25356595,  1.04891887, -0.91105419, -1.45069404,  0.80168814,
       -0.35723404,  0.67883101,  0.35161432,  0.11011863, -1.78380287,
       -0.05648857,  1.88507624, -0.14934399,  0.52509984, -1.25136625,
        0.95024936,  0.15132685, -0.16174675, -0.32326896,  1.03018689])

In [195]:
np.mean(a)

0.17022836116912402

In [196]:
np.std(a)

1.01635098073643

In [197]:
np.var(a)

1.032969316043903

In [198]:
np.median(a)

0.13072274054171304

In [199]:
sum(a)

5.106850835073719

np.nanmean(a)

np.nanstd(a)

np.nanvar(a)

np.nanargmin(a) 

np.nanargmax(a) 

np.nanmedian(a)

In [200]:
np.min(a)

-1.7838028665852717

In [201]:
np.max(a)

2.199459565502093

In [202]:
a = np.random.normal(0, 1, (3,3))
a

array([[ 1.07058606, -0.6120382 ,  0.76638259],
       [-0.17595975, -0.74605335,  0.85442668],
       [ 0.65979535,  0.35306437,  0.20976902]])

In [203]:
a.sum()

2.379972775698564

In [204]:
a.sum(axis = 1)

array([ 1.22493045, -0.06758642,  1.22262874])

# Farklı Boyutlu Arrayler ile Birlikte Çalışmak (broadcasting)

In [205]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

a + b

array([2, 4, 6])

In [206]:
m = np.ones((3, 3))
m

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [207]:
a

array([1, 2, 3])

In [208]:
a + m

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [209]:
a = np.arange(3)
a

array([0, 1, 2])

In [210]:
b = np.arange(3)[:, np.newaxis]
b

array([[0],
       [1],
       [2]])

In [211]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [212]:
M = np.ones((2, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [213]:
a = np.arange(3)
a

array([0, 1, 2])

In [214]:
a + M

array([[1., 2., 3.],
       [1., 2., 3.]])

In [215]:
a = np.arange(3).reshape((3, 1))
a

array([[0],
       [1],
       [2]])

In [216]:
b = np.arange(3)
b

array([0, 1, 2])

In [217]:
a.shape

(3, 1)

In [218]:
b.shape

(3,)

In [219]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [220]:
m = np.ones((3,2))
m

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [221]:
a = np.arange(3)
a

array([0, 1, 2])

In [222]:
m.shape

(3, 2)

In [223]:
a.shape

(3,)

# Numpy Yapısal Array'ler

## Hello! Good Bye! Numpy

In [224]:
isim = ['ali', 'veli', 'isik']
yas = [25, 22, 19]
boy = [168, 159, 172]

In [225]:
data = np.zeros(3, dtype={'names':('isim', 'yas', 'boy'),
                          'formats':('U10', 'i4', 'f8')})

In [226]:
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [227]:
data['isim'] = isim
data['yas'] = yas
data['boy'] = boy

In [228]:
data

array([('ali', 25, 168.), ('veli', 22, 159.), ('isik', 19, 172.)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [229]:
data['isim']

array(['ali', 'veli', 'isik'], dtype='<U10')

In [230]:
data[0]

('ali', 25, 168.)

In [231]:
data[data['yas'] < 25]['isim']

array(['veli', 'isik'], dtype='<U10')

# Pandas

## Pandas Series

In [232]:
import numpy as np
import pandas as pd

In [233]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [234]:
seri = pd.Series([1,2,3,4])

In [235]:
type(seri)

pandas.core.series.Series

In [236]:
seri.axes

[RangeIndex(start=0, stop=4, step=1)]

In [237]:
seri.dtype

dtype('int64')

In [238]:
seri.empty

False

In [239]:
seri.ndim

1

In [240]:
seri.size

4

In [241]:
seri.values

array([1, 2, 3, 4], dtype=int64)

In [242]:
seri.head(2)

0    1
1    2
dtype: int64

In [243]:
seri[0:3]

0    1
1    2
2    3
dtype: int64

In [244]:
seri.tail(2)

2    3
3    4
dtype: int64

In [245]:
a = np.array([1,2,3,566,88])
a

array([  1,   2,   3, 566,  88])

In [246]:
type(a)

numpy.ndarray

In [247]:
seri = pd.Series(a)

In [248]:
seri

0      1
1      2
2      3
3    566
4     88
dtype: int32

In [249]:
seri.index

RangeIndex(start=0, stop=5, step=1)

In [250]:
seri[0]

1

In [251]:
pd.Series([1,5,0.9,34], index = [1,3,5,7])

1     1.0
3     5.0
5     0.9
7    34.0
dtype: float64

In [252]:
seri = pd.Series([1,5,0.9,34], index = ['a','b','c','d'])

In [253]:
seri["a"]

1.0

In [254]:
sozluk = { "reg" : 10, "loj" : 11, "cart" : 12}

In [255]:
sozluk

{'reg': 10, 'loj': 11, 'cart': 12}

In [256]:
seri = pd.Series(sozluk)

In [257]:
seri["reg"]

10

In [258]:
seri["loj":"cart"]

loj     11
cart    12
dtype: int64

In [259]:
seri

reg     10
loj     11
cart    12
dtype: int64

In [260]:
pd.concat([seri, seri])

reg     10
loj     11
cart    12
reg     10
loj     11
cart    12
dtype: int64

In [261]:
seri.append(seri)

reg     10
loj     11
cart    12
reg     10
loj     11
cart    12
dtype: int64

In [262]:
seri

reg     10
loj     11
cart    12
dtype: int64

## Serilerde Eleman İşlemleri

In [263]:
a = np.array([1, 2, 3,33,55,66])
seri = pd.Series(a)
seri

0     1
1     2
2     3
3    33
4    55
5    66
dtype: int32

In [264]:
seri[0]

1

In [265]:
seri[0:3]

0    1
1    2
2    3
dtype: int32

In [266]:
seri = pd.Series([121, 200, 150, 99], 
                 index=["reg", "loj", "cart", "rf"])
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [267]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [268]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [269]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [270]:
seri.values

array([121, 200, 150,  99], dtype=int64)

In [271]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [272]:
"reg" in seri

True

In [273]:
seri["reg"]

121

In [274]:
seri[['rf', 'reg']]

rf      99
reg    121
dtype: int64

In [275]:
seri["rf"] = 125

In [276]:
seri

reg     121
loj     200
cart    150
rf      125
dtype: int64

In [277]:
seri['loj': 'rf']

loj     200
cart    150
rf      125
dtype: int64

In [278]:
seri[0:2]

reg    121
loj    200
dtype: int64

In [279]:
seri = pd.Series([121, 200, 150, 99], index=["reg", "loj", "cart", "rf"])
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [280]:
seri[(seri > 125) & (seri < 200)]

cart    150
dtype: int64

In [281]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [282]:
data[0]

KeyError: 0

In [ ]:
data[1]

In [ ]:
data[1:3]

In [ ]:
data[0:3]

In [ ]:
# loc label based indexing, tanımlandığı şekli ile index yakalamak

In [ ]:
data

In [ ]:
data.loc[0:5]

In [ ]:
# iloc positional indexing, indexi sıfırlayarak yakalamak

In [ ]:
data

In [ ]:
data.iloc[2]

In [ ]:
data.iloc[0:3]